export class PostApartment {
    constructor(
        private country:string,
        private address:string,
        private city:string,
        private state:string,
        private postcode:number,
        private type:string,
        private bedroom:number,
        private bathroom:number,
        private contact:string,
        private begining:string,
        private ending:string,
        private rent:number,
        private otherCharge:number,
        private discripition:string,
        private furniture:boolean,
        private TV:boolean,
        private wifi:boolean,
        private airConditioner:boolean,
        private alarm:boolean,
        private guard:boolean,
        private gym:boolean,
        private swimmingPool:boolean,
        private parkinglot:boolean,
        private washingMachine:boolean,
        private noPet:boolean,
        private noSmoking:boolean,
        private noStaying:boolean,
        private noParty:boolean,
    ){}
}
